services:
  web:
    build: .
    container_name: php_eduweb
    ports:
      - "8000:80"
    volumes:
      - ./php-src:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: mysql-eduweb
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=5uP3R__54iY4n
      - MYSQL_DATABASE=eduwebdb
      - MYSQL_USER=eduweb
      - MYSQL_PASSWORD=5uP3R__54iY4n
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./tables.sql:/docker-entrypoint-initdb.d/tables.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 5uP3R__54iY4n
    ports:
      - "8080:80"
    depends_on:
      - db